print("CALCULO PARA VER EL SALARIO NETO")
salario_base = int(input("ingresa el salario base"))
horas_extras = int(input("ingresa las horas extras"))
pago_hora_extra = int(input("ingresa el pago por horas extras"))
bono = int(input("ingresan el bono"))
afp = int(input("ingresa el monto del AFP"))
salud = int(input("monto de salud"))
salario_neto = salario_base + (horas_extras * pago_hora_extra) + bono - (salario_base * afp/100) - (salario_base * salud/100)
salario_bruto = salario_base + (horas_extras * pago_hora_extra) + bono - (salario_base * afp/100)
descuentos_totales = (salario_base * salud/100)
print("SALARIO NETO: " + int(salario_neto))
print("SALARIO BRUTO:" + int(salario_bruto))
print("DESCUENTOS TOTALES: " + int(descuentos_totales))